### PR TITLE
Fixup enkf main alloc

### PR DESCRIPTION
**Pull request by pgdr**
**Task**
Update call site in `main.c` after Statoil/libres#66 changed signature of `enkf_main_alloc`.

**Pre un-WIP checklist**
- [x] Statoil tests pass locally
- [x] Have completed graphical integration test steps

### CODE REVIEW

**Comment by markusdregi** [comment]
Looks good!

**Comment by pgdr** [comment]
@joakim-hove The Travis pr builder crashes (due to the link to a closed PR?).

**Comment by joakim-hove** [comment]
Well - yes, it will find the closed pr #66, and fail hard on that - because it is closed.

**Comment by joakim-hove** [comment]
I meant - check the code for the or builder, i.e. verify that the applications are built. 

I am on phone now.

**Pull request merged**
