### PR TITLE
Travis builder work on closed pr

### PR DESCRIPTION
**Pull request by pgdr**
**Task**

The PR builder should not crash when you refer to closed PRs in a description.

Also added build libres with `-Werror=all`.

### CODE REVIEW

**Comment by pgdr** [comment]
> Do we need the ctest label?

yes

**Comment by markusdregi** [comment]
What happens when reffering to a closed PR? Do we build towards master?

**Comment by pgdr** [comment]
To elaborate.  We have the option of running 5 parallel jobs, but we use just one today.  One way to utilize the multiple jobs is to label the tests into several labels and let the different jobs do different test suites.

**Comment by pgdr** [comment]
> What happens when reffering to a closed PR? Do we build towards master?

Yes.  As per now I believe we only support mentioning _one_ PR per repo, and if that is closed, we shouldn't crash, but build towards master instead.

**Pull request merged**
